import type { Metadata } from "next"
import { Outfit, Bricolage_Grotesque } from "next/font/google"
import "./globals.css"
import Header from "./_components/header"

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
})

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body
        className={`${outfit.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
